services:
  mailhog:
    image: mailhog/mailhog
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./mailhog-app/data:/data
    ports:
      - "1025:1025" # Desbloquar a porta do firewall
    networks:
      web:
        ipv4_address: 10.0.9.28
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.mailhog.rule=Host(`mailhog.test.wilsoncastro.dev`)"
        - "traefik.http.routers.mailhog.entrypoints=https"
        - "traefik.http.routers.mailhog.tls=true"
        - "traefik.http.routers.mailhog.tls.certresolver=letsencrypt"
        - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Mailhog" no ambiente de teste
# sudo docker stack deploy -c docker-compose.mailhog.test.yml mailhog

# Implanta uma stack do serviço "Mailhog" no ambiente de teste
# sudo docker stack deploy -c docker-compose.mailhog.production.yml mailhog

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Mailhog"
# sudo docker service ps mailhog_mailhog

# Exibe os logs do serviço "Mailhog"
# sudo docker service logs mailhog_mailhog

# Remove o serviço "Mailhog" do ambiente de teste
# sudo docker stack rm mailhog