services:
  duplicati:
    image: linuxserver/duplicati
    environment:
      - TZ=America/Sao_Paulo
    networks:
      web:
        ipv4_address: 10.0.9.13
    volumes:
      - ./duplicati-app/config:/config
      - ./duplicati-app/backups:/backups
      - /home/ubuntu/services:/source
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.duplicati.rule=Host(`duplicati.test.wilsoncastro.dev`)"
        - "traefik.http.routers.duplicati.entrypoints=https"
        - "traefik.http.routers.duplicati.tls=true"
        - "traefik.http.routers.duplicati.tls.certresolver=letsencrypt"
        - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Duplicati" no ambiente de teste
# sudo docker stack deploy -c docker-compose.duplicati.test.yml duplicati

# Implanta uma stack do serviço "Duplicati" no ambiente de teste
# sudo docker stack deploy -c docker-compose.duplicati.production.yml duplicati

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Duplicati"
# sudo docker service ps duplicati_duplicati

# Exibe os logs do serviço "Duplicati"
# sudo docker service logs duplicati_duplicati

# Remove o serviço "Duplicati" do ambiente de teste
# sudo docker stack rm duplicati