services:
  vaultwarden:
    image: vaultwarden/server
    environment:
      - TZ=America/Sao_Paulo
      - ROCKET_TLS_DISABLE=1
    networks:
      web:
        ipv4_address: 10.0.9.42
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.test.wilsoncastro.dev`)"
        - "traefik.http.routers.vaultwarden.entrypoints=https"
        - "traefik.http.routers.vaultwarden.tls=true"
        - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=3012"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Vaultwarden" no ambiente de teste
# sudo docker stack deploy -c docker-compose.vaultwarden.test.yml vaultwarden

# Implanta uma stack do serviço "Vaultwarden" no ambiente de teste
# sudo docker stack deploy -c docker-compose.vaultwarden.production.yml vaultwarden

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Vaultwarden"
# sudo docker service ps vaultwarden_vaultwarden

# Exibe os logs do serviço "Vaultwarden"
# sudo docker service logs vaultwarden_vaultwarden

# Remove o serviço "Vaultwarden" do ambiente de teste
# sudo docker stack rm vaultwarden