services:
  example:
    image: example
    environment:
      - TZ=America/Sao_Paulo
    networks:
      web:
        ipv4_address: 10.0.9.7
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.example.rule=Host(`example.test.wilsoncastro.dev`)"
        - "traefik.http.routers.example.entrypoints=https"
        - "traefik.http.routers.example.tls=true"
        - "traefik.http.routers.example.tls.certresolver=letsencrypt"
        - "traefik.http.services.example.loadbalancer.server.port=8080"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "example" no ambiente de teste
# sudo docker stack deploy -c docker-compose.example.test.yml example

# Implanta uma stack do serviço "example" no ambiente de teste
# sudo docker stack deploy -c docker-compose.example.production.yml example

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "example"
# sudo docker service ps example_example