services:
  adminer:
    image: adminer
    environment:
      - TZ=America/Sao_Paulo
    networks:
      web:
        ipv4_address: 10.0.9.10
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.adminer.rule=Host(`adminer.test.wilsoncastro.dev`)"
        - "traefik.http.routers.adminer.entrypoints=https"
        - "traefik.http.routers.adminer.tls=true"
        - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Adminer" no ambiente de teste
# sudo docker stack deploy -c docker-compose.adminer.test.yml adminer

# Implanta uma stack do serviço "Adminer" no ambiente de teste
# sudo docker stack deploy -c docker-compose.adminer.production.yml adminer

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço adminer_adminer
# sudo docker service ps adminer_adminer

# Exibe os logs do serviço "Adminer"
# sudo docker service logs adminer_adminer

# Remove o serviço "Adminer" do ambiente de teste
# sudo docker stack rm adminer