services:
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://login.wilsoncastro.dev/realms/services
      - PROVIDERS_OIDC_CLIENT_ID=services
      - PROVIDERS_OIDC_CLIENT_SECRET=aITE3I1kfQRwAEP7dwng4dQ1aowHuwYK
      - SECRET=2WqLAeKqrOUtHYzE # pwgen -N 1 -s 16
    depends_on:
      - traefik
    networks:
      web:
        ipv4_address: 10.0.9.6
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.services.forward-auth.loadbalancer.server.port=4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-Forwarded-Proto, X-Forwarded-Uri, X-Forwarded-For, X-Forwarded-Method, X-Secret"
        - "traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Traefik-forward-auth" no ambiente de teste
# sudo docker stack deploy -c docker-compose.traefik-forward-auth.test.yml traefik-forward-auth

# Implanta uma stack do serviço "Traefik-forward-auth" no ambiente de teste
# sudo docker stack deploy -c docker-compose.traefik-forward-auth.production.yml traefik-forward-auth

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Traefik-forward-auth"
# sudo docker service ps traefik-forward-auth_traefik-forward-auth

# Exibe os logs do serviço "Traefik-forward-auth"
# sudo docker service logs traefik-forward-auth_traefik-forward-auth

# Remove o serviço "Traefik-forward-auth" do ambiente de teste
# sudo docker stack rm traefik-forward-auth