services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    volumes:
      - ./jenkins-app/jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    environment:
      - TZ=America/Sao_Paulo
    networks:
      web:
        ipv4_address: 10.0.9.53
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.test.wilsoncastro.dev`)"
        - "traefik.http.routers.jenkins.entrypoints=https"
        - "traefik.http.routers.jenkins.tls=true"
        - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
        - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Jenkins" no ambiente de teste
# sudo docker stack deploy -c docker-compose.jenkins.test.yml jenkins

# Implanta uma stack do serviço "Jenkins" no ambiente de teste
# sudo docker stack deploy -c docker-compose.jenkins.production.yml jenkins

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Jenkins"
# sudo docker service ps jenkins_jenkins

# Exibe os logs do serviço "Jenkins"
# sudo docker service logs jenkins_jenkins

# Remove o serviço "Jenkins" do ambiente de teste
# sudo docker stack rm jenkins