services:
  vault:
    image: hashicorp/vault
    environment:
      - TZ=America/Sao_Paulo
      - VAULT_ADDR=http://vault:8200
    command: vault server -config=/vault/config/config.hcl
    volumes:
      - ./vault-app/config:/vault/config
      - ./vault-app/vault/file:/vault/file
    cap_add:
      - IPC_LOCK
    networks:
      web:
        ipv4_address: 10.0.9.55
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.vault.rule=Host(`vault.test.wilsoncastro.dev`)"
        - "traefik.http.routers.vault.entrypoints=https"
        - "traefik.http.routers.vault.tls=true"
        - "traefik.http.routers.vault.tls.certresolver=letsencrypt"
        - "traefik.http.services.vault.loadbalancer.server.port=8200"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Vault" no ambiente de teste
# sudo docker stack deploy -c docker-compose.vault.test.yml vault

# Implanta uma stack do serviço "Vault" no ambiente de teste
# sudo docker stack deploy -c docker-compose.vault.production.yml vault

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Vault"
# sudo docker service ps vault_vault

# Exibe os logs do serviço "Vault"
# sudo docker service logs vault_vault

# Remove o serviço "Vault" do ambiente de teste
# sudo docker stack rm vault