services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-app/data:/data
    networks:
      web:
        ipv4_address: 10.0.9.31
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.portainer.rule=Host(`portainer.test.wilsoncastro.dev`)"
        - "traefik.http.routers.portainer.entrypoints=https"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Portainer" no ambiente de teste
# sudo docker stack deploy -c docker-compose.portainer.test.yml portainer

# Implanta uma stack do serviço "Portainer" no ambiente de teste
# sudo docker stack deploy -c docker-compose.portainer.production.yml portainer

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Portainer"
# sudo docker service ps portainer_portainer

# Exibe os logs do serviço "Portainer"
# sudo docker service logs portainer_portainer

# Remove o serviço "Portainer" do ambiente de teste
# sudo docker stack rm portainer