services:
  netdata:
    image: netdata/netdata
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    networks:
      web:
        ipv4_address: 10.0.9.29
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.http.routers.netdata.rule=Host(`netdata.test.wilsoncastro.dev`)"
        - "traefik.http.routers.netdata.entrypoints=https"
        - "traefik.http.routers.netdata.tls=true"
        - "traefik.http.routers.netdata.tls.certresolver=letsencrypt"
        - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s

networks:
  web:
    external: true

# Implanta uma stack do serviço "Netdata" no ambiente de teste
# sudo docker stack deploy -c docker-compose.netdata.test.yml netdata

# Implanta uma stack do serviço "Netdata" no ambiente de teste
# sudo docker stack deploy -c docker-compose.netdata.production.yml netdata

# Lista serviços Docker em execução
# sudo docker service ls

# Lista detalhes específicos do serviço "Netdata"
# sudo docker service ps netdata_netdata

# Exibe os logs do serviço "Netdata"
# sudo docker service logs netdata_netdata

# Remove o serviço "Netdata" do ambiente de teste
# sudo docker stack rm netdata